---
title: "Midterm: Ice Cream"
author: ""
# date: "today"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes a lot of the helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
# Once installed, load the library.
library(ezids)
```


```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

```{r import_data}
getwd()
products <- data.frame(read.csv("products.csv", header = TRUE))
str(products)
head(products)

reviews <- data.frame(read.csv("reviews.csv", header = TRUE))
str(reviews)
head(reviews)
```

```{r results='markup'}
colnames(products)[1:8]=c("Brand", "Product ID", "Product Name", "Subhead","Product Description", "Rating", "Rating Count", "Ingredients")
xkabledplyhead(products, title = "Product header rows")

colnames(reviews)[1:13]=c("Brand", "Product ID", "Username", "Date", "Stars", "Title", "Helpful", "Not Helpful", "Review", "Taste", "Ingredients", "Texture", "Likes")
xkabledplyhead(reviews, title = "Review header rows")
```

# Exploratory Data Analysis

```{r}
library(ggplot2)
ggplot(data=products, aes(Rating)) +
  geom_histogram(col='blue', fill='lightblue', alpha=0.7) +
    labs(x="Rating", y="Frequency") +
    labs(title="Ice Cream Product Rating Histogram using `ggplot`")
```

This histogram shows the overall ratings of all ice-cream products across all 4 brands of ice-cream. We can see that there is a high frequency of ratings within the 4 - 5 star range.

```{r results='markup'}
mean.ratings <- mean(products$Rating)
mean.ratings
```

### Ben & Jerry's

```{r}
bj_data <- subset(products, Brand == "bj")

library(ggplot2)
ggplot(bj_data, aes(Rating)) +
  geom_histogram(col='yellow', fill='black', alpha=0.7) +
  labs(x="Rating", y="Frequency") +
  labs(title="Ben & Jerry's Product Rating Histogram using `ggplot`")
```

```{r results='markup'}
mean.bjratings <- mean(bj_data$Rating)
mean.bjratings
```

### Häagen-Dazs

```{r}
hd_data <- subset(products, Brand == "hd")

library(ggplot2)
ggplot(hd_data, aes(Rating)) +
  geom_histogram(col='brown', fill='tan', alpha=0.7) +
  labs(x="Rating", y="Frequency") +
  labs(title="Häagen-Dazs' Product Rating Histogram using `ggplot`")
```

```{r results='markup'}
mean.hdratings <- mean(hd_data$Rating)
mean.hdratings
```

### Talenti

```{r}
talenti_data <- subset(products, Brand == "talenti")

library(ggplot2)
ggplot(talenti_data, aes(Rating)) +
  geom_histogram(col='brown', fill='white', alpha=0.7) +
  labs(x="Rating", y="Frequency") +
  labs(title="Talenti's Product Rating Histogram using `ggplot`")
```

```{r results='markup'}
mean.talratings <- mean(talenti_data$Rating)
mean.talratings
```

### Breyers

```{r}
breyers_data <- subset(products, Brand == "breyers")

library(ggplot2)
ggplot(breyers_data, aes(Rating)) +
  geom_histogram(col='white', fill='green', alpha=0.7) +
  labs(x="Rating", y="Frequency") +
  labs(title="Breyers' Product Rating Histogram using `ggplot`")
```

```{r results='markup'}
mean.breyratings <- mean(breyers_data$Rating)
mean.breyratings
```